trigger: none  # pas de déclenchement automatique

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self  # le dépôt GitHub est déjà lié

  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '8.0.117'

  - script: dotnet restore NeedABreak.Updater.sln
    displayName: 'dotnet restore'

  - script: dotnet build --configuration Release NeedABreak.Updater.sln
    displayName: 'dotnet build'
