trigger: none  # pas de déclenchement automatique

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self  # le dépôt GitHub est déjà lié

  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '8.0.117'

  - task: dependabot@2
    inputs:
      gitHubConnection: 'bNobo'
      gitHubAccessToken: '$(GITHUB_PAT)'