//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeedABreak.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeedABreak.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About NEED A BREAK!.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the wait time before lockdown.
        /// </summary>
        internal static string ajuster_le_delai {
            get {
                return ResourceManager.GetString("ajuster_le_delai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string annuler {
            get {
                return ResourceManager.GetString("annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically determine when &quot;Do not disturb&quot; mode should be activated.
        /// </summary>
        internal static string automatic_suspension {
            get {
                return ResourceManager.GetString("automatic_suspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app automatically enable &quot;Do not disturb&quot; mode when it detects that a full-screen app or presentation has started and automatically reactivates when the full-screen app or presentation is complete..
        /// </summary>
        internal static string automatic_suspension_tooltip {
            get {
                return ResourceManager.GetString("automatic_suspension_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEED A BREAK!  Copyright (C) 2020  Benoit Rocco.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup.
        /// </summary>
        internal static string executer_au_demarrage {
            get {
                return ResourceManager.GetString("executer_au_demarrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup (controlled by administrator).
        /// </summary>
        internal static string executer_au_demarrage_admin_disabled {
            get {
                return ResourceManager.GetString("executer_au_demarrage_admin_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup (disabled by user).
        /// </summary>
        internal static string executer_au_demarrage_user_disabled {
            get {
                return ResourceManager.GetString("executer_au_demarrage_user_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When working on a screen, it is important to take frequent screen breaks based on your work hours. Choose the appropriate work duration.
        /// </summary>
        internal static string explications {
            get {
                return ResourceManager.GetString("explications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string fermer {
            get {
                return ResourceManager.GetString("fermer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        internal static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s break time!.
        /// </summary>
        internal static string il_est_l_heure {
            get {
                return ResourceManager.GetString("il_est_l_heure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imminent lockdown.
        /// </summary>
        internal static string Imminent_locking {
            get {
                return ResourceManager.GetString("Imminent_locking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INRS.
        /// </summary>
        internal static string inrs {
            get {
                return ResourceManager.GetString("inrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than a minute to lockdown.
        /// </summary>
        internal static string Less_than_a_minute_before_locking {
            get {
                return ResourceManager.GetString("Less_than_a_minute_before_locking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view full license.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock now.
        /// </summary>
        internal static string lock_now {
            get {
                return ResourceManager.GetString("lock_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:##} minutes to lockdown.
        /// </summary>
        internal static string minutes_before_locking {
            get {
                return ResourceManager.GetString("minutes_before_locking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:%h} hours.
        /// </summary>
        internal static string n_hours {
            get {
                return ResourceManager.GetString("n_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:%h} hours, {0:%m} minutes.
        /// </summary>
        internal static string n_hours_n_minutes {
            get {
                return ResourceManager.GetString("n_hours_n_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:%m} minutes.
        /// </summary>
        internal static string n_minutes {
            get {
                return ResourceManager.GetString("n_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification before locking.
        /// </summary>
        internal static string notification_avant_verrouillage {
            get {
                return ResourceManager.GetString("notification_avant_verrouillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string one_hour {
            get {
                return ResourceManager.GetString("one_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour, {0:%m} minutes.
        /// </summary>
        internal static string one_hour_n_minutes {
            get {
                return ResourceManager.GetString("one_hour_n_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        internal static string one_minute {
            get {
                return ResourceManager.GetString("one_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One minute to lockdown.
        /// </summary>
        internal static string one_minute_before_locking {
            get {
                return ResourceManager.GetString("one_minute_before_locking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string quitter {
            get {
                return ResourceManager.GetString("quitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpone.
        /// </summary>
        internal static string reporter {
            get {
                return ResourceManager.GetString("reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string resume {
            get {
                return ResourceManager.GetString("resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable &quot;Do not disturb&quot; mode..
        /// </summary>
        internal static string resume_tooltip {
            get {
                return ResourceManager.GetString("resume_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Do not disturb&quot; mode disabled..
        /// </summary>
        internal static string resumed_message {
            get {
                return ResourceManager.GetString("resumed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivated.
        /// </summary>
        internal static string resumed_title {
            get {
                return ResourceManager.GetString("resumed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not disturb.
        /// </summary>
        internal static string suspend {
            get {
                return ResourceManager.GetString("suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable &quot;Do not disturb&quot; mode..
        /// </summary>
        internal static string suspend_tooltip {
            get {
                return ResourceManager.GetString("suspend_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Do not disturb&quot; mode enabled.
        /// </summary>
        internal static string suspended_message {
            get {
                return ResourceManager.GetString("suspended_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEED A BREAK! (do not disturb).
        /// </summary>
        internal static string suspended_title {
            get {
                return ResourceManager.GetString("suspended_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s screen time: {0}.
        /// </summary>
        internal static string today_screen_time {
            get {
                return ResourceManager.GetString("today_screen_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text in english.
        /// </summary>
        internal static string translation_test {
            get {
                return ResourceManager.GetString("translation_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usual work.
        /// </summary>
        internal static string travail_habituel {
            get {
                return ResourceManager.GetString("travail_habituel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive work.
        /// </summary>
        internal static string travail_intensif {
            get {
                return ResourceManager.GetString("travail_intensif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low-intensive work.
        /// </summary>
        internal static string travail_peu_intensif {
            get {
                return ResourceManager.GetString("travail_peu_intensif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very intensive work.
        /// </summary>
        internal static string travail_tres_intensif {
            get {
                return ResourceManager.GetString("travail_tres_intensif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (undefined).
        /// </summary>
        internal static string undefined {
            get {
                return ResourceManager.GetString("undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screen will be locked in less than a minute. Remember to save your changes!.
        /// </summary>
        internal static string verrouillage_imminent_detail {
            get {
                return ResourceManager.GetString("verrouillage_imminent_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMMINENT LOCKDOWN.
        /// </summary>
        internal static string verrouillage_imminent_title {
            get {
                return ResourceManager.GetString("verrouillage_imminent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program comes with ABSOLUTELY NO WARRANTY;.
        /// </summary>
        internal static string warranty {
            get {
                return ResourceManager.GetString("warranty", resourceCulture);
            }
        }
    }
}
