//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeedABreak.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeedABreak.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de NEED A BREAK!.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajuster le délai.
        /// </summary>
        internal static string ajuster_le_delai {
            get {
                return ResourceManager.GetString("ajuster_le_delai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string annuler {
            get {
                return ResourceManager.GetString("annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer automatiquement le mode &quot;Ne pas déranger&quot;.
        /// </summary>
        internal static string automatic_suspension {
            get {
                return ResourceManager.GetString("automatic_suspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;application se met automatiquement en mode &quot;Ne pas déranger&quot; lorsqu&apos;elle détecte qu&apos;une application plein écran ou une présentation a démarré et se réactive automatiquement lorsque l&apos;application plein écran ou la présentation est terminé..
        /// </summary>
        internal static string automatic_suspension_tooltip {
            get {
                return ResourceManager.GetString("automatic_suspension_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact :.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEED A BREAK!  Copyright (C) 2020  Benoit Rocco.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exécuter au démarrage.
        /// </summary>
        internal static string executer_au_demarrage {
            get {
                return ResourceManager.GetString("executer_au_demarrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorsqu&apos;on travaille sur écran, il est impératif de respecter un régime de pauses qui doit être fonction de l&apos;intensité du travail. Choisissez le délai approprié en fonction de l&apos;intensité du travail que vous devez accomplir..
        /// </summary>
        internal static string explications {
            get {
                return ResourceManager.GetString("explications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string fermer {
            get {
                return ResourceManager.GetString("fermer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ici.
        /// </summary>
        internal static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il est l&apos;heure de bouger !.
        /// </summary>
        internal static string il_est_l_heure {
            get {
                return ResourceManager.GetString("il_est_l_heure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verrouillage imminent.
        /// </summary>
        internal static string Imminent_locking {
            get {
                return ResourceManager.GetString("Imminent_locking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INRS.
        /// </summary>
        internal static string inrs {
            get {
                return ResourceManager.GetString("inrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moins d&apos;une minute avant verrouillage.
        /// </summary>
        internal static string Less_than_a_minute_before_locking {
            get {
                return ResourceManager.GetString("Less_than_a_minute_before_locking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez consulter la licence complète.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verrouiller.
        /// </summary>
        internal static string lock_now {
            get {
                return ResourceManager.GetString("lock_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:##} minutes avant verrouillage.
        /// </summary>
        internal static string minutes_before_locking {
            get {
                return ResourceManager.GetString("minutes_before_locking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification avant verrouillage.
        /// </summary>
        internal static string notification_avant_verrouillage {
            get {
                return ResourceManager.GetString("notification_avant_verrouillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une minute avant verrouillage.
        /// </summary>
        internal static string one_minute_before_locking {
            get {
                return ResourceManager.GetString("one_minute_before_locking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string quitter {
            get {
                return ResourceManager.GetString("quitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        internal static string reporter {
            get {
                return ResourceManager.GetString("reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprendre.
        /// </summary>
        internal static string resume {
            get {
                return ResourceManager.GetString("resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver le mode &quot;Ne pas déranger&quot;.
        /// </summary>
        internal static string resume_tooltip {
            get {
                return ResourceManager.GetString("resume_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode &quot;Ne pas déranger&quot; désactivé.
        /// </summary>
        internal static string resumed_message {
            get {
                return ResourceManager.GetString("resumed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réactivation.
        /// </summary>
        internal static string resumed_title {
            get {
                return ResourceManager.GetString("resumed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pas déranger.
        /// </summary>
        internal static string suspend {
            get {
                return ResourceManager.GetString("suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer le mode &quot;Ne pas déranger&quot;..
        /// </summary>
        internal static string suspend_tooltip {
            get {
                return ResourceManager.GetString("suspend_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode &quot;Ne pas déranger&quot; activé.
        /// </summary>
        internal static string suspended_message {
            get {
                return ResourceManager.GetString("suspended_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEED A BREAK! (Ne pas déranger).
        /// </summary>
        internal static string suspended_title {
            get {
                return ResourceManager.GetString("suspended_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travail habituel.
        /// </summary>
        internal static string travail_habituel {
            get {
                return ResourceManager.GetString("travail_habituel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travail intensif.
        /// </summary>
        internal static string travail_intensif {
            get {
                return ResourceManager.GetString("travail_intensif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travail peu intensif.
        /// </summary>
        internal static string travail_peu_intensif {
            get {
                return ResourceManager.GetString("travail_peu_intensif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travail très intensif.
        /// </summary>
        internal static string travail_tres_intensif {
            get {
                return ResourceManager.GetString("travail_tres_intensif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (non défini).
        /// </summary>
        internal static string undefined {
            get {
                return ResourceManager.GetString("undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le poste va se verrouiller dans moins d&apos;une minute. Pensez à sauvegardez vos modifications !.
        /// </summary>
        internal static string verrouillage_imminent_detail {
            get {
                return ResourceManager.GetString("verrouillage_imminent_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERROUILLAGE IMMINENT.
        /// </summary>
        internal static string verrouillage_imminent_title {
            get {
                return ResourceManager.GetString("verrouillage_imminent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce programme est fourni SANS AUCUNE GARANTIE;.
        /// </summary>
        internal static string warranty {
            get {
                return ResourceManager.GetString("warranty", resourceCulture);
            }
        }
    }
}
